baseurl = "http://example.org/"
languageCode = "en-us"
title = "Hugo Cards"
theme = "hugo cards"
themesDir = "themes"
paginate = 6
baseURL = ""
publishDir = "public"

[params]
builtBy = "bool"
defaultImage = "gopher.jpg"
facebook = ""
quora = ""
twitter = "http://twitter.com/bul_ikana"
github = "http://github.com/bul-ikana"
email = ""
fbLikeBox = ""
fbAppId = ""
fbPageUrl = ""
fbPageTitle = ""
analytics = ""
disqus = ""
custom_css = [ "css/custom.css" ]

  [params.copyright]
  name = "bool"
  link = "https://bool.netlify.com"
